# Generated by Django 3.2.9 on 2022-02-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquitecturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=40)),
                ('num_lista', models.IntegerField()),
                ('num_sku', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=40)),
                ('num_sku', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrecioNeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=40)),
                ('num_lista', models.IntegerField()),
                ('num_sku', models.IntegerField()),
            ],
        ),
    ]
